import { createHash } from 'node:crypto';
import type { Plugin } from 'vite';

/**
 * Emits a hand-rolled precaching service worker (`sw.js`) whose cache name is
 * derived from the content hashes of the emitted bundle, so every deploy
 * invalidates the previous cache exactly once.
 */
export function injectServiceWorker(): Plugin {
  return {
    name: 'coldpaper:sw',
    apply: 'build',
    generateBundle(_options, bundle) {
      const files = Object.keys(bundle).filter((f) => !f.endsWith('.map'));
      // public/ files are copied outside the bundle; list them explicitly.
      const extra = [
        'manifest.webmanifest',
        'favicon.svg',
        'icons/icon-192.png',
        'icons/icon-512.png',
        'icons/maskable-512.png',
        'icons/apple-touch-icon.png',
        'coldpaper-offline.html',
      ];
      const precache = ['./', ...files.map((f) => `./${f}`), ...extra.map((f) => `./${f}`)];
      const version = createHash('sha256').update(JSON.stringify(precache)).digest('hex').slice(0, 12);
      const source = `// generated by plugins/sw-plugin.ts - do not edit
const CACHE = 'coldpaper-${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== location.origin) return;
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(request)
          .then((response) => {
            if (response.ok) {
              const copy = response.clone();
              caches.open(CACHE).then((cache) => cache.put(request, copy));
            }
            return response;
          })
          .catch(() => (request.mode === 'navigate' ? caches.match('./') : Promise.reject(new Error('offline')))),
    ),
  );
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source });
    },
  };
}
